maint: Switch from `print -P %F{col-nr}` to `m {col-name}`.
zdharma-continuum/zinit-annex-bin-gem-node pull request #19
Opened 2022-12-24 09:17 UTC by psprint

The `m` function is automatically provided for the moment of loading/installing a plugin and it's the same as `+zinit-message`. With this patch, `bgn` annex will support theming from https://github.com/zdharma-continuum/zinit/pull/445.

## Description 

`s/print -P --/m …` 
## Motivation and Context 
To make messages from `bgn` annex follow `$ZITHEME` themes.

## Related Issue(s) 

https://github.com/zdharma-continuum/zinit/pull/445.

## Usage examples 

```zsh
m {pre}bgn-annex:{warn} returned code is {num}1
```

## How Has This Been Tested? 

## Types of changes 

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist: 

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-01-31 09:16 UTC, psprint commented
@vladdoster when merge?

2023-01-31 22:40 UTC, vladdoster commented
@psprint, 

Why not use `+zinit-message`? 

Regardless, the `m` function needs to be renamed to follow convention (i.e., `+`, `.`, etc.) and give more context about what the function does.

2023-01-31 22:41 UTC, vladdoster requested changes
@psprint, 

Why not use `+zinit-message`? 

Regardless, the `m` function needs to be renamed to follow convention (i.e., `+`, `.`, etc.) and give more context about what the function does.

2023-02-01 07:05 UTC, psprint commented
The m function is outside the convention because it's for atclone and similar ices - to be as shortest as possible. However here are atclone hooks not ices so I understand that it can be better to use its full name. Should I change it?

2023-04-20 05:50 UTC, vladdoster commented
This breaks the annex.

<img width="512" alt="Screenshot 2023-04-20 at 00 09 42" src="https://user-images.githubusercontent.com/10052309/233269993-b2e73896-0457-40f6-9a7c-b88cfb6dff4b.png">

2023-04-20 05:50 UTC, closed without merging